// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDconz6_NUxLFJu9odT7dcR2CcWqrfRPnI',
    appId: '1:868007322820:web:f551421915c73059cc9591',
    messagingSenderId: '868007322820',
    projectId: 'finealflutter',
    authDomain: 'finealflutter.firebaseapp.com',
    storageBucket: 'finealflutter.appspot.com',
    measurementId: 'G-LJ56ZZZGGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMoKHq2jsNi2wyUgh07Q2EgN2m6qsPfpA',
    appId: '1:868007322820:android:61e8ecc2499b8ff7cc9591',
    messagingSenderId: '868007322820',
    projectId: 'finealflutter',
    storageBucket: 'finealflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfHK0CCc_wEvs45eQsCqQw0T93nki7d1w',
    appId: '1:868007322820:ios:9c711d2652667cbecc9591',
    messagingSenderId: '868007322820',
    projectId: 'finealflutter',
    storageBucket: 'finealflutter.appspot.com',
    iosBundleId: 'com.example.finalExamFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfHK0CCc_wEvs45eQsCqQw0T93nki7d1w',
    appId: '1:868007322820:ios:9c711d2652667cbecc9591',
    messagingSenderId: '868007322820',
    projectId: 'finealflutter',
    storageBucket: 'finealflutter.appspot.com',
    iosBundleId: 'com.example.finalExamFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDconz6_NUxLFJu9odT7dcR2CcWqrfRPnI',
    appId: '1:868007322820:web:9241742f4adb3471cc9591',
    messagingSenderId: '868007322820',
    projectId: 'finealflutter',
    authDomain: 'finealflutter.firebaseapp.com',
    storageBucket: 'finealflutter.appspot.com',
    measurementId: 'G-P9LTKQZ401',
  );
}
